version: '3.7'

services:

  backend:
    container_name: flask-container
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    entrypoint: python run.py
    env_file:
      - backend/.env
    depends_on:
      - redis
      - postgres

  redis:
    container_name: redis-container
    build:
      context: ./redis
      dockerfile: Dockerfile.redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
    - ./redis/redis-jwt-data:/data
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf

  postgres:
    container_name: postgres-container
    build:
      context: ./postgres
      dockerfile: Dockerfile.postgres
    env_file:
      - backend/.env

  frontend:
    container_name: react-datta-container
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:80'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
