version: '3.7'

services:

  api:
    container_name: flask-container
    build:
      context: ./server
      dockerfile: Dockerfile.server
    entrypoint: python run.py
    env_file:
      - server/.env
    depends_on:
      - redis
      - postgres

  redis:
    container_name: redis-container
    build:
      context: ./_deployment/redis
      dockerfile: Dockerfile.redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
    - ./_deployment/redis/redis-jwt-data:/data
    - ./_deployment/redis/redis.conf:/usr/local/etc/redis/redis.conf

  postgres:
    container_name: postgres-container
    build:
      context: ./_deployment/postgres
      dockerfile: Dockerfile.postgres
    env_file:
      - server/.env

  client:
    container_name: react-datta-container
    build:
      context: .
      dockerfile: ./client/Dockerfile.client
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:80'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
